image: archlinux
packages:
  - rust
  - libpulse
sources:
  - https://git.sr.ht/~kennylevinsen/wldash
tasks:
  - rustfmt-check: |
      cd wldash
      cargo fmt -- --check
  - build: |
      cd wldash
      cargo build
